services:
    postgres:
      container_name: postgres_database
      image: postgres:13
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: prix_banque_dev
      ports:
        - '5432:5432'
      volumes: 
        - ./data/db:/var/lib/postgresql/data
        - ./sql/create.sql:/docker-entrypoint-initdb.d/create.sql

    account:
      container_name: account_microservice
      build: ./account/
      ports:
        - '8000:8000'

    transfer:
      container_name: transfer_microservice
      build: ./transfer/
      ports:
        - '8001:8001'

    invoice:
      container_name: invoice_microservice
      build: ./invoice/
      ports:
        - '8002:8002'

    nginx:
      container_name: nginx_reverseproxy
      image: nginx
      ports:
        - '8080:80'
      volumes: 
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
